/** Подготовка к вакансии «Волга-Волга». Источник опыта: resume-source.txt и исходники двух проектов. */
export type PrepItem = {
  title: string
  requirement: string
  answer: string
  example: string
  evidence?: string
  status: 'practice' | 'adjacent' | 'learn'
}

export const stack: PrepItem[] = [
  { title: 'React 19, хуки, композиция, Suspense', requirement: 'Разделять логику по хукам, понимать границы Suspense и правила хуков.', answer: 'В Themost клиент на React 19. Общую логику выношу в хуки и небольшие компоненты; тяжёлые экраны подключаю через React.lazy и Suspense. Suspense обрабатывает ожидание lazy-компонента, но обычный useEffect-запрос сам по себе в него не попадает.', example: 'Themost: ленивые маршруты карт, KYC и операций. Jumpster: React 18 и отдельная lazy-загрузка экрана упражнения.', evidence: 'themost-core/tma-template/client/src/navigation/routes.tsx; service-core/client/src/App.tsx', status: 'practice' },
  { title: 'Vite и TypeScript', requirement: 'Сборка SPA, интерфейсы, дженерики, типизация API.', answer: 'Оба клиента собираются Vite и написаны на TypeScript. В Themost типы tRPC связывают клиент с API-контрактом; для данных извне дополнительно проверяю форму в runtime, потому что TypeScript исчезает после сборки.', example: 'Themost: tRPC-клиент и схема ответа bootstrap. Jumpster: типизированный tRPC-клиент.', evidence: 'themost-core/tma-template/client/src/app/AppBootstrap.tsx; service-core/client/src/trpc/client.ts', status: 'practice' },
  { title: 'zod на границе API', requirement: 'Валидация данных, которые пришли из сети.', answer: 'Типы не защищают от сломанного JSON. На границе разбираю unknown через zod.safeParse, затем показываю управляемое состояние ошибки. В Themost это сделано для bootstrap-ответа.', example: 'Themost: bootstrapSchema.safeParse(value).', evidence: 'themost-core/tma-template/client/src/app/AppBootstrap.tsx', status: 'practice' },
  { title: 'Tailwind CSS 4, CVA, CSS Modules', requirement: 'Стили и вариативные компоненты.', answer: 'Tailwind 4 есть в Themost. CVA в изученных package.json не найден: объясню модель variants и compoundVariants и быстро внедрю в компонентную библиотеку. CSS Modules выберу для локального сложного оформления, когда утилитарные классы ухудшают читаемость.', example: 'Themost использует Tailwind 4; Jumpster — Tailwind 3 и Sass. CVA не стоит выдавать за внедрённый опыт.', evidence: 'themost-core/tma-template/client/package.json; service-core/client/package.json', status: 'adjacent' },
  { title: 'TanStack React Query', requirement: 'Кеш, ключи, инвалидация, оптимистичные обновления.', answer: 'В Themost запросы и мутации живут в React Query: ключи привязаны к сущности, после мутации инвалидируется нужный запрос. Оптимистичное изменение допустимо для обратимых UI-действий; финансовый статус я подтверждаю сервером. Если нужен optimistic update: cancelQueries → snapshot → setQueryData → rollback в onError → invalidate в onSettled.', example: 'Themost: funding-hooks обновляет active intent и инвалидирует intent после отмены.', evidence: 'themost-core/tma-template/client/src/features/funding/api/funding-hooks.ts', status: 'practice' },
  { title: 'ky как HTTP-клиент', requirement: 'Уметь настроить клиент, хуки, ошибки и повторные запросы.', answer: 'В моих проектах использован tRPC, а не ky. Для REST на ky сделал бы единый instance с prefixUrl, beforeRequest для токена, afterResponse для 401 и ограниченным refresh/retry без бесконечного цикла. Контракт данных валидировал бы zod.', example: 'Themost и Jumpster: tRPC; прямого опыта ky в этих репозиториях нет.', status: 'learn' },
  { title: 'Zustand и разделение состояний', requirement: 'Клиентское состояние отдельно от серверного.', answer: 'В проектах клиентское состояние организовано другими средствами: Redux Toolkit в Jumpster, React Query и локальное состояние в Themost. Zustand подошёл бы для небольшого клиентского store, но данные API оставил бы в React Query, иначе получу два кеша и ручную синхронизацию.', example: 'Jumpster: redux/slices; Themost: QueryClientProvider и feature hooks.', evidence: 'service-core/client/src/redux/slices/appSlice.ts; themost-core/tma-template/client/src/components/Root.tsx', status: 'adjacent' },
  { title: 'SPA: роутинг, guards, persistence', requirement: 'Маршруты, защита, восстановление состояния.', answer: 'В Jumpster есть RequireAuth и React Router; в Themost маршруты и bootstrap с проверкой сессии. Guard на клиенте улучшает UX, но не заменяет проверку доступа на сервере. Хранить между сессиями стоит только данные с понятной политикой истечения.', example: 'Jumpster: RequireAuth; Themost: AppBootstrap и navigation/routes.', evidence: 'service-core/client/src/hoc/RequireAuth.tsx; themost-core/tma-template/client/src/app/AppBootstrap.tsx', status: 'practice' },
  { title: 'Telegram Mini Apps SDK', requirement: 'Авторизация, viewport, back button, нативные жесты.', answer: 'Работал с Telegram WebApp API и @telegram-apps/sdk-react. initData передаётся на сервер для проверки подписи; initDataUnsafe не считаю доказательством личности. Высоту беру из WebView и реагирую на viewportChanged. Back button связываю с логическими родительскими маршрутами, потому что browser history после платежа или cold start ненадёжен.', example: 'Jumpster: useTelegramViewport/useTelegramBackButton. Themost: host-navigation и resolveTelegramBackAction.', evidence: 'service-core/client/src/hooks/useTelegramViewport.ts; themost-core/tma-template/client/src/components/Page.tsx', status: 'practice' },
  { title: 'Lazy loading, code splitting, Profiler, memo', requirement: 'Измерять до оптимизации.', answer: 'Themost делит код по маршрутам через React.lazy; Jumpster откладывает тяжёлый экран упражнения. При жалобе на рендер сначала React DevTools Profiler: нахожу дорогой commit и причину. memo/useMemo/useCallback использую, когда есть измеренная цена рендера или важна стабильная ссылка, а не повсюду.', example: 'Themost: navigation/routes.tsx; Jumpster: App.tsx.', evidence: 'themost-core/tma-template/client/src/navigation/routes.tsx; service-core/client/src/App.tsx', status: 'practice' },
  { title: 'REST, GraphQL, CORS', requirement: 'Клиентские контракты и ограничения браузера.', answer: 'Работал с API через tRPC и REST-подобные сценарии. GraphQL понимаю на уровне query/mutation, кеша и схемы, но в этих двух проектах он не основной транспорт. CORS задаёт сервер: preflight возникает при нестандартных заголовках/методах; настройка frontend не может снять запрет браузера.', example: 'Jumpster: заголовок x-tg-auth в tRPC; Themost: типизированные процедуры.', evidence: 'service-core/client/src/trpc/client.ts', status: 'adjacent' },
  { title: 'JWT, refresh и 401', requirement: 'Безопасная сессия и восстановление.', answer: 'Themost использует сессионные сценарии с Telegram proof и JWT по резюме. При 401 один refresh для параллельных запросов, затем повтор исходного запроса один раз; если refresh неуспешен — очистка состояния и повторная авторизация. Секреты не кладу в URL; хранение токена выбираю по угрозам WebView и серверному контракту.', example: 'Themost: client-lock-flow требует свежий Telegram proof при восстановлении сессии.', evidence: 'themost-core/tma-template/client/src/features/client-lock/client-lock-flow.ts', status: 'practice' },
  { title: 'Figma, адаптивность и a11y', requirement: 'Точный UI, семантика, focus management, контраст.', answer: 'Работаю по макету с контрольными ширинами и состояниями loading/empty/error. Для интерактивных элементов использую button/link, видимый focus, подписи полей и управление фокусом в диалогах; ARIA добавляю там, где нативной семантики не хватает. В Telegram дополнительно проверяю клавиатуру и safe area.', example: 'Themost: настройки viewport и тесты экранов. Jumpster: адаптация тренировочного UI под WebView.', evidence: 'themost-core/tma-template/client/src/init.test.ts; service-core/client/src/hooks/useTelegramViewport.ts', status: 'practice' },
  { title: 'Vitest, RTL, review, CI/CD', requirement: 'Проверка поведения и командный стандарт.', answer: 'В Themost есть Vitest и React Testing Library, в Jumpster тесты логики. Тестирую поведение пользователя и критические переходы. Перед сдачей запускаю typecheck, lint, тесты и build; в review обсуждаю контракт и крайние случаи. Preview deployment полезен для проверки WebView и дизайна на реальном устройстве.', example: 'Themost: тесты back button, funding и bootstrap. Jumpster: тесты pose/helper и платежных сценариев.', evidence: 'themost-core/tma-template/client/src/components/components.test.tsx; service-core/client/src/helpers/pose-helper.squat.test.ts', status: 'practice' },
]

export const hr: PrepItem[] = [
  { title: 'Расскажите о себе', requirement: 'Ответ на 60–90 секунд', answer: 'Я frontend/fullstack разработчик с опытом 3+ лет, основной стек — React и TypeScript. В Jumpster довёл Telegram Mini App от UI тренировок и работы с камерой до интеграции с API и продакшена. В Themost делал клиент финтех Mini App: онбординг, карты, KYC, платежные сценарии, тесты. Мне интересна роль, где можно сосредоточиться на качестве frontend и использовать мой опыт с Mini Apps.', example: 'Не перечислять весь backend; держать акцент на задачах вакансии.', status: 'practice' },
  { title: 'Почему хотите к нам?', requirement: 'Мотивация без выдуманных фактов о компании', answer: 'Меня привлекло сочетание React 19, TypeScript, современной работы с данными и платформенных SDK. В моих последних проектах Mini Apps были ключевым продуктом, поэтому могу быстро включиться в задачи с Telegram и WebView. На встрече хочу понять продукт, команду и критерии успеха роли.', example: 'Уточнить конкретный продукт Волга-Волга на интервью.', status: 'practice' },
  { title: 'В чём ваша сильная сторона?', requirement: 'Доказуемый пример', answer: 'Умею разбирать сложный пользовательский сценарий целиком: UI, состояние, API и ошибки. В Themost для карточных и платёжных потоков это важно: пользователь должен видеть корректный статус, даже если ответ провайдера задержался или приложение открылось повторно.', example: 'Themost: funding intent, опрос статуса и возврат после платежа.', evidence: 'themost-core/tma-template/client/src/features/funding/api/funding-hooks.ts', status: 'practice' },
  { title: 'Ошибка или сложная ситуация', requirement: 'Признать проблему, действие и урок', answer: 'В Mini App обычная история браузера оказалась ненадёжной после cold start и платёжного возврата. Я перенёс логику Back на явные родительские маршруты и добавил тесты. Теперь до реализации навигации отдельно проверяю контракт хост-платформы.', example: 'Themost: resolveTelegramBackAction и тесты Page.', evidence: 'themost-core/tma-template/client/src/components/Page.tsx', status: 'practice' },
  { title: 'Как спорите с дизайнером или backend?', requirement: 'Конструктивная коммуникация', answer: 'Сначала уточняю пользовательский сценарий и ограничение. Показываю конкретный конфликт: например, WebView перекрывает нижнюю кнопку клавиатурой. Предлагаю 1–2 варианта с последствиями для UX и сроков, фиксируем решение и проверяем его на устройстве.', example: 'Опирайтесь на viewport/keyboard задачи Mini Apps, не придумывая конфликт с конкретным коллегой.', status: 'practice' },
  { title: 'Неполное ТЗ и изменение требований', requirement: 'Уточнение и самостоятельность', answer: 'До оценки спрашиваю о целевом сценарии, состояниях ошибок, API, платформе и критерии готовности. Разбиваю работу на небольшие шаги. Когда требование меняется, отдельно называю затронутые экраны, контракт, тесты и новую оценку.', example: 'Для выпуска карты уточнить повторный запрос, idempotency key, pending и отказ провайдера.', status: 'practice' },
  { title: 'Оценка, задержки, трекер и часы', requirement: 'Организация работы', answer: 'Оцениваю отдельно UI, интеграцию, проверки и неизвестные зависимости. Обновляю задачу по фактическому прогрессу и времени; как только вижу риск срока, сообщаю причину, новый прогноз и возможный более узкий объём. На сдачу прикладываю способ проверки.', example: 'Не называйте конкретный трекер или метод учёта часов, если это не отражено в опыте.', status: 'practice' },
  { title: 'Ревью, обратная связь и юмор', requirement: 'Командная культура', answer: 'В ревью отделяю факт от вкусового предпочтения: если замечание улучшает надёжность или читаемость — исправляю; если есть компромисс, объясняю его спокойно и предлагаю проверяемый вариант. В неформальном общении легко поддерживаю контакт, но в рабочих обсуждениях держу ясные договорённости.', example: 'Говорить естественно, без заученной шутки.', status: 'practice' },
]

export const tricky: PrepItem[] = [
  { title: 'Почему Redux, а не MobX или Zustand?', requirement: 'Выбор state manager', answer: 'В Jumpster Redux Toolkit уже подходил для общего клиентского состояния и предсказуемого потока обновлений. MobX был в Task Tracker из резюме — там я работал в существующей архитектуре. Zustand рассмотрел бы для небольшого нового client state, но не мигрировал бы работающий продукт только ради библиотеки. Server state оставил бы React Query/tRPC.', example: 'Jumpster: Redux slices; Task Tracker: MobX по резюме; Themost: React Query.', evidence: 'service-core/client/src/redux/slices/appSlice.ts', status: 'practice' },
  { title: 'Почему React 18 в Jumpster, если нужен React 19?', requirement: 'Версии и миграция', answer: 'Jumpster стартовал на React 18, а Themost уже работает на React 19. Обновление большого приложения я делаю по совместимости библиотек, тестам и измеренному эффекту, а не ради номера версии. React 19 в продакшен-коде Themost мне знаком.', example: 'Версии подтверждаются client/package.json двух проектов.', status: 'practice' },
  { title: 'Почему tRPC, а в вакансии ky/REST?', requirement: 'Транспорт и перенос навыков', answer: 'tRPC даёт сквозную типизацию в TypeScript монорепозитории. ky — удачный HTTP-клиент для REST, когда контракт отдельный или backend другого стека. Работа с таймаутами, ошибками, auth, повтором запроса и проверкой ответа переносится; синтаксис ky освою быстро. Готов показать, как организовал бы instance и 401-flow.', example: 'Не утверждать, что ky уже использовался.', status: 'adjacent' },
  { title: 'Почему не делали всё оптимистично?', requirement: 'Корректность данных', answer: 'В финансовом потоке локальная «успешная» запись может обмануть пользователя. Для обратимого UI переключателя optimistic update уместен с rollback. Для баланса и выпуска карты показываю pending и подтверждаю результат с сервера, затем инвалидирую кеш.', example: 'Themost: funding intent polling и инвалидация после мутации.', evidence: 'themost-core/tma-template/client/src/features/funding/api/funding-hooks.ts', status: 'practice' },
  { title: 'Зачем zod, если есть TypeScript и tRPC?', requirement: 'Граница доверия', answer: 'TypeScript проверяет исходники, а не реальные байты ответа. Даже при tRPC внешняя интеграция, старая версия клиента или невалидный payload могут нарушить ожидания. Для критичного bootstrap использую runtime schema и явную ветку ошибки.', example: 'Themost: bootstrapSchema.safeParse.', evidence: 'themost-core/tma-template/client/src/app/AppBootstrap.tsx', status: 'practice' },
  { title: 'JWT в localStorage безопасен?', requirement: 'Модель угроз', answer: 'localStorage доступен JavaScript, поэтому XSS делает токен уязвимым. HttpOnly cookie снижает этот риск, но в Mini Apps cookies могут вести себя нестабильно из-за WebView и окружения. Выбор зависит от backend-контракта: короткий access token, контролируемое обновление, проверка Telegram proof на сервере и защита от XSS.', example: 'Не обещать универсально безопасный способ хранения.', status: 'practice' },
  { title: 'Что если Telegram Back и браузерный Back расходятся?', requirement: 'Навигация хост-платформы', answer: 'Сначала задаю семантический маршрут возврата и обрабатываю модальные состояния. В Themost после платёжного возврата или cold start нельзя надёжно полагаться на history, поэтому Back ведёт к вычисленному родительскому экрану. Подписку на кнопку обязательно снимаю при размонтировании.', example: 'Themost: Page и host-navigation; Jumpster: useTelegramBackButton.', evidence: 'themost-core/tma-template/client/src/components/Page.tsx; service-core/client/src/hooks/useTelegramBackButton.ts', status: 'practice' },
  { title: 'Почему fullstack разработчик идёт на frontend?', requirement: 'Фокус роли', answer: 'Мой основной интерес и сильная сторона — сложный интерактивный frontend. Backend-опыт помогает мне лучше проектировать API-контракты, состояния ошибок и обсуждать решения с серверной командой. В этой роли хочу отвечать за качество клиентского продукта.', example: 'Подкрепить сценарием карты или тренировки.', status: 'practice' },
  { title: 'Где у вас нет прямого опыта?', requirement: 'Честная оценка пробелов', answer: 'В этих проектах не вижу применения ky, CVA, Zustand и VK Mini Apps SDK. У меня есть близкий опыт: tRPC/HTTP, компонентные стили, Redux/MobX, Telegram SDK. Могу объяснить решения и освоить конкретный API, но не буду выдавать его за уже внедрённый.', example: 'Такой ответ лучше проверить практическим заданием, чем скрывать различия.', status: 'learn' },
]
