import type { Question } from '@/engine/types'

export const databasesDeepQuestions: Question[] = [
  { id:'db-join-left-where', theoryId:'th-postgres-mysql', topic:'Базы данных', type:'manual', level:'middle',
    q:'Нужно вывести каждого клиента, включая клиентов без оплаченных заказов, и их количество. Напишите запрос и объясните, почему условие статуса важно поставить в ON, а не в WHERE.',
    solution:`SELECT c.id, COUNT(o.id) AS paid_count
FROM customers c
LEFT JOIN orders o ON o.customer_id = c.id AND o.status = 'paid'
GROUP BY c.id;`,
    answer:`<p>LEFT JOIN сохраняет каждую строку клиента. Условие paid ставим в ON: у клиента без оплаченного заказа справа останется NULL, он попадёт в результат, а COUNT(o.id) даст ноль. Если условие o.status='paid' перенести в WHERE, строки с NULL отфильтруются и результат фактически станет INNER JOIN. COUNT(*) посчитает строку клиента как единицу, поэтому для нуля считаем nullable ключ правой таблицы.</p>` },
  { id:'db-join-explosion-practice', theoryId:'th-postgres-mysql', topic:'Базы данных', type:'manual', level:'senior',
    q:'Заказ имеет 4 позиции и 3 тега. После двух LEFT JOIN запрос возвращает 12 строк на заказ, SUM(price) завышена. Объясните причину и предложите подход.',
    solution:'Это fan-out: каждая позиция комбинируется с каждым тегом. Агрегировать позиции и теги отдельно в CTE/subquery до JOIN, либо загрузить отдельными запросами. Не применять SUM(DISTINCT price): две реальные позиции могут иметь одинаковую цену.',
    answer:`<p>Две коллекции one-to-many дают произведение совпадений: 4 позиции × 3 тега = 12 строк. Цена позиции повторяется три раза, поэтому SUM завышена. Агрегируйте позиции и теги независимо по order_id в подзапросах/CTE, затем соедините агрегаты с заказом, либо загрузите коллекции отдельными запросами. SUM(DISTINCT price) неверен: разные позиции с одинаковой ценой должны обе учитываться. Проверяйте количество строк до ORM-гидрации.</p>` },
  { id:'db-isolation-engines', theoryId:'th-postgres-mysql', topic:'Базы данных', type:'theory', level:'senior',
    q:'Чем отличается REPEATABLE READ в PostgreSQL и InnoDB/MySQL и почему недостаточно назвать только уровень изоляции?',
    answer:`<p>Нужно назвать движок и тип чтения. PostgreSQL REPEATABLE READ даёт snapshot isolation: обычные чтения внутри транзакции видят один snapshot, обычного phantom read нет, но возможен write skew; SERIALIZABLE может завершить транзакцию ошибкой сериализации, которую приложение иногда ограниченно повторяет. InnoDB по умолчанию REPEATABLE READ; consistent reads используют snapshot, а locking reads/range access могут брать gap/next-key locks. Версия, индекс и тип запроса влияют на поведение, поэтому ярлык SQL-уровня не описывает полностью блокировки.</p>` },
  { id:'db-conditional-update', theoryId:'th-postgres-mysql', topic:'Базы данных', type:'manual', level:'middle',
    q:'Два запроса одновременно покупают последнюю единицу товара. Покажите атомарный SQL-подход и объясните, что проверит приложение.',
    solution:`UPDATE inventory SET available = available - 1
WHERE sku = 'A-1' AND available > 0;
-- продолжать только если affected rows === 1`,
    answer:`<p>Условный UPDATE уменьшает количество только если оно положительно. База согласует конфликтующие изменения строки; только один запрос изменит последнюю единицу. Приложение проверяет affected rows: 1 означает успешный резерв, 0 — товара больше нет или SKU не найден. Заказ и резерв при необходимости связываются транзакцией и constraints. Не читайте остаток в Node, а затем безусловно записывайте вычисленное значение — так возникает lost update.</p>` },
  { id:'db-explain-index-choice', theoryId:'th-postgres-mysql', topic:'Базы данных', type:'choice', level:'middle',
    q:'В плане большой таблицы PostgreSQL показывает Seq Scan. Что корректнее сказать?',
    options:[{t:'Изучить actual rows и стоимость: последовательное сканирование может быть правильным, если запрос читает большую долю таблицы',ok:true},{t:'Любой Seq Scan доказывает отсутствие индекса и медленную работу',ok:false},{t:'Создать индекс на каждом поле WHERE независимо от частоты записи',ok:false}],
    answer:`<p>Планировщик сравнивает стоимость. Если читается большая доля таблицы или таблица маленькая, последовательное чтение дешевле случайных чтений через индекс. Проверьте actual rows, loops, buffers, сортировки и estimate. Если оценки ошибочны, изучите статистику и корреляцию; затем подберите индекс по реальному предикату и измерьте повторно. Один Seq Scan сам по себе не означает проблему.</p>` },
  { id:'db-mysql-primary-key', theoryId:'th-postgres-mysql', topic:'Базы данных', type:'theory', level:'middle',
    q:'Почему размер и выбор primary key важны для InnoDB?',
    answer:`<p>InnoDB организует строки clustered index по primary key. Вторичные индексы хранят свой ключ и значение primary key для доступа к строке. Поэтому длинный VARCHAR PK повторяется в каждом secondary index, увеличивая диск, память и I/O. Компактный стабильный ключ помогает, но также учитывайте локальность вставок: случайный UUID может ухудшить заполнение страниц. Бизнес-уникальность при необходимости закрепляют отдельным unique index.</p>` },
  { id:'redis-cache-practice', theoryId:'th-redis-deep', topic:'Кеш и очереди', type:'manual', level:'middle',
    q:'Спроектируйте cache-aside для профиля: ключ, TTL, запись после обновления и поведение при одновременном истечении популярного ключа.',
    solution:'Использовать ключ user:{id}:profile:v{version}; GET, при miss читать DB и SET EX с TTL+jitter. После DB commit удалить/сменить версию ключа, учесть гонку старого загрузчика. Hot miss смягчить single-flight/lock или stale-while-revalidate; кеш не источник истины.',
    answer:`<p>Ключ включает namespace/version и user id. На miss читаем базу и ставим TTL плюс jitter, чтобы много ключей не истекали одновременно. После commit изменения инвалидируем или увеличиваем версию ключа; медленный старый запрос может записать устаревшее значение уже после удаления, это нужно учитывать. Для горячего ключа single-flight, короткий lock или stale-while-revalidate уменьшают stampede. При отказе Redis используем контролируемый fallback, но бизнес-инвариант проверяем в базе.</p>` },
  { id:'redis-lock-practice', theoryId:'th-redis-deep', topic:'Кеш и очереди', type:'manual', level:'senior',
    q:'Опишите безопасный минимальный Redis lock и объясните, почему SET lock 1 плюс DEL lock опасен.',
    solution:'Атомарно SET key unique-token NX PX leaseMs; release Lua проверяет совпадение token перед DEL. TTL не оставляет lock навечно, но владелец может работать после истечения lease; критичной операции нужен fencing token или DB constraint/transaction.',
    answer:`<p>SET с уникальным owner token, NX и PX атомарно захватывает lock и задаёт lease. Освобождение выполняют скриптом: удалить только если значение всё ещё равно token текущего владельца. Иначе старый процесс мог зависнуть, lease истёк, новый процесс взял lock, а первый позднее удалил его. Даже owner check не решает работу старого владельца после истечения lease; критичный ресурс должен проверять fencing version либо обеспечивать инвариант DB constraint/transaction.</p>` },
  { id:'redis-pubsub-stream-choice', theoryId:'th-redis-deep', topic:'Кеш и очереди', type:'choice', level:'middle',
    q:'Нужно, чтобы отключённый consumer после reconnect обработал сообщения, отправленные во время его отсутствия. Что выбрать?',
    options:[{t:'Pub/Sub недостаточно: нужен persistent stream, например Redis Streams с consumer group или Kafka',ok:true},{t:'Redis Pub/Sub хранит и переигрывает пропущенные сообщения',ok:false},{t:'TTL Pub/Sub задаёт персональный offset consumer',ok:false}],
    answer:`<p>Pub/Sub рассылает только активным подписчикам: истории и подтверждения нет. Для накопления и replay используйте Redis Streams с consumer groups/pending entries или Kafka в зависимости от throughput, retention и независимых групп. В любом варианте продумайте ack, повтор, retention и идемпотентность: сохранённое сообщение ещё не означает exactly-once внешний эффект.</p>` },
  { id:'kafka-ordering', theoryId:'th-kafka-deep', topic:'Кеш и очереди', type:'theory', level:'middle',
    q:'Как обеспечить порядок событий одного заказа в Kafka и какой компромисс возникает у partition key?',
    answer:`<p>Используйте orderId как key, чтобы события одного заказа попадали в одну partition; порядок гарантируется внутри неё. Consumer не должен сам разрушать его параллельной обработкой. Компромисс: hot key может создать перегруженную partition, а число partitions ограничивает параллелизм. Глобального порядка всего topic нет; изменение числа partitions способно изменить распределение будущих событий.</p>` },
  { id:'kafka-offset-practice', theoryId:'th-kafka-deep', topic:'Кеш и очереди', type:'manual', level:'senior',
    q:'Consumer обрабатывает записи асинхронно с concurrency=10 и commit-ит максимальный завершённый offset. Как может потеряться запись при рестарте?',
    solution:'Если offset 10 завершился до 9 и commit продвинул позицию за 10, рестарт начнёт после 10, хотя offset 9 ещё не обработан. Commit только непрерывный prefix завершённых offsets по каждой partition либо сохранять последовательную обработку.',
    answer:`<p>Offset commit задаёт, откуда группа продолжит чтение. Если offset 10 завершился раньше 9 и consumer commit-нул позицию за 10, после рестарта запись 9 будет пропущена. Для каждой partition учитывайте непрерывный префикс завершённых обработок и commit-ьте только безопасную следующую позицию. Либо сохраняйте последовательную обработку внутри partition. Повторы при падении всё равно возможны, поэтому обработчик должен быть идемпотентным.</p>` },
  { id:'kafka-exactly-once-choice', theoryId:'th-kafka-deep', topic:'Кеш и очереди', type:'choice', level:'senior',
    q:'Что означает exactly-once в Kafka и где это обещание заканчивается?',
    options:[{t:'Kafka transactions могут атомаризовать consume-transform-produce внутри Kafka, но не запись в произвольную внешнюю БД/API',ok:true},{t:'Idempotent producer гарантирует ровно одно выполнение email и платежа',ok:false},{t:'Ручной commit исключает и потери, и дубликаты без дополнительной логики',ok:false}],
    answer:`<p>Kafka transactions могут атомарно записать output records и offsets consumed input внутри Kafka pipeline; downstream читает committed данные с подходящим isolation level. Idempotent producer дедуплицирует повторы в своей поддерживаемой границе. Email, PostgreSQL и платёжный API не входят автоматически в Kafka transaction. Для них нужны outbox/inbox, idempotency key, unique constraints и reconciliation. Всегда уточняйте границу exactly-once, а не называйте её свойством всей распределённой системы.</p>` },
]
