import type { TheoryArticle } from '@/engine/types'

export const networkProtocols: TheoryArticle = { id:'th-network-protocols', topic:'Сетевые протоколы', title:'Сетевые протоколы в глубину: TCP, DNS, TLS, HTTP/2–3, WebSocket и RPC',
  lead:'Механика популярных протоколов, handshake и состояния, границы гарантий, типичные сбои, выбор транспорта и лабораторные наблюдения пакетного потока.',
  body:`
<h5>Протокол — это контракт, а не просто формат байтов</h5>
<p>Протокол определяет, как стороны находят друг друга, согласуют возможности, кодируют сообщения, подтверждают получение, сообщают ошибки, поддерживают совместимость и завершают взаимодействие. Слои строятся друг на друге: приложение использует транспорт, транспорт — сеть, сеть — канальный уровень. У каждой гарантии есть граница: TCP гарантирует упорядоченный поток байт между endpoints, но не то, что сервер обработал бизнес-операцию; HTTP кодирует семантику запроса, но не гарантирует доступность БД.</p>
<p>При выборе протокола задавайте вопросы: нужна ли доставка и порядок, допустима ли потеря, есть ли request/response или stream, требуется ли browser support, как проходит firewall/proxy, где аутентификация, какие ограничения frame/message, как диагностировать и версионировать контракт.</p>

<h5>TCP подробно: sequence numbers, ACK, окна и congestion control</h5>
<p>TCP разбивает byte stream на сегменты с sequence number. Приёмник подтверждает полученную позицию ACK; потеря может обнаруживаться по таймеру retransmission или нескольким одинаковым ACK. Sliding receive window сообщает, сколько данных приёмник способен принять, — это flow control. Congestion window ограничивает отправителя из-за оценки перегрузки сети, — это congestion control. Их минимум ограничивает объём данных «в полёте».</p>
<p>Bandwidth-delay product (пропускная способность × RTT) оценивает, сколько байт нужно держать в пути для полной утилизации канала. Малое окно на линии с высоким RTT ограничивает throughput. Packet loss вызывает retransmission и обычно уменьшает congestion window, поэтому длинный RTT и даже небольшой loss сильно влияют на скорость.</p>
<p>TCP не сохраняет границы write/read. Приложение обязано определить framing: фиксированная длина, delimiter с escaping или length-prefix. Частые ошибки: один read ожидали равным одному message, не ограничили длину frame, не обработали half-close, забыли timeout и создали неограниченный буфер.</p>

<h5>Состояния соединения, backlog и TIME_WAIT</h5>
<p>TCP соединение проходит LISTEN, SYN-SENT/SYN-RECEIVED, ESTABLISHED и закрывающие состояния FIN-WAIT/CLOSE-WAIT/TIME-WAIT. CLOSE_WAIT обычно означает, что peer закрыл соединение, а локальное приложение ещё не закрыло socket — возможна утечка соединений. TIME_WAIT нужен для безопасного завершения старого потока сегментов; это не автоматически «утечка», но массовое короткоживущее соединение создаёт нагрузку на порты/ресурсы.</p>
<p>На сервере SYN backlog хранит незавершённые handshakes; accept queue — уже установленные соединения, ожидающие accept приложением. Параметры ОС, backlog в приложении, reverse proxy и connection rate влияют на насыщение. Диагностируйте через <code class="i">ss -s</code>, <code class="i">ss -tan state syn-recv</code> и counters ядра; не меняйте sysctl наугад, если узким местом медленный handler.</p>

<h5>TLS 1.3: что согласуется при handshake</h5>
<p>ClientHello объявляет версии, наборы cipher suites, key share, extensions и обычно SNI hostname. Сервер выбирает параметры, присылает сертификат и доказательство владения приватным ключом, стороны формируют общие session keys. TLS 1.3 сокращает handshake и удаляет ряд устаревших алгоритмов; сертификатная проверка клиентом подтверждает цепочку и имя. Для аутентификации клиента требуется отдельная схема, например mTLS или application credentials.</p>
<p>Session resumption снижает стоимость повторного handshake. 0-RTT может отправить данные раньше, но ранние данные подвержены replay, поэтому должны быть безопасны к повтору (обычно только подходящие идемпотентные запросы). TLS не скрывает IP адреса и весь metadata потока; DNS может быть видим без DoH/DoT, а SNI традиционно виден, если не используются новые механизмы защиты.</p>

<h5>DNS: итеративность, рекурсия и DNSSEC</h5>
<p>Stub resolver клиента отправляет рекурсивный запрос своему resolver. Recursive resolver выполняет итеративные обращения к root hints, TLD и authoritative servers, кеширует положительные и отрицательные ответы и возвращает результат клиенту. DNS обычно использует UDP, но может использовать TCP при больших ответах, truncation, zone transfer и иных условиях. EDNS(0) расширяет возможности DNS сообщений, включая допустимый размер UDP ответа.</p>
<p>DNSSEC подписывает DNS данные и позволяет validating resolver проверять цепочку доверия через DS/DNSKEY/RRSIG. DNSSEC подтверждает целостность/происхождение данных, но сам по себе не шифрует запрос и не скрывает домен. DoT и DoH шифруют канал до выбранного resolver, но доверие переносится к этому resolver. DNS CAA может ограничивать, какие CA выпускают сертификат домену.</p>
<p>Кешировать может браузер, OS stub, локальный resolver, корпоративный DNS и public recursive resolver. Из-за этого изменение записи имеет распределённую задержку. TTL — максимум обычного positive caching, но negative caching и локальная политика тоже важны. Round-robin DNS не заменяет полноценный health-aware load balancing.</p>

<h5>HTTP/1.1: методы, framing и persistent connections</h5>
<p>HTTP сообщение содержит start line, headers, пустую строку и body. Сообщение тела определяется Content-Length или chunked transfer coding; некорректная неоднозначность между прокси и backend может стать request smuggling уязвимостью. HTTP/1.1 keep-alive позволяет многократно использовать connection, но один последовательный pipeline ограничен head-of-line ожиданием ответа; браузеры открывали несколько соединений к origin.</p>
<p>Методы несут семантику: GET безопасен и должен быть идемпотентен по намерению; PUT и DELETE идемпотентны по HTTP semantics, POST обычно нет, хотя сервер может реализовать idempotency key. Safe не означает «без побочных эффектов в логах», а идемпотентность не означает одинаковый response при каждом повторе. Коды ответа и cache headers участвуют в поведении клиента/proxy.</p>

<h5>HTTP/2: multiplexing и HPACK</h5>
<p>HTTP/2 кодирует бинарные frames внутри одного TCP соединения. Несколько logical streams могут чередовать frames, что уменьшает блокировку на уровне HTTP ответа. Headers сжимаются HPACK с таблицами; server push был малоэффективен в массовом применении и браузерная поддержка изменилась. Потеря TCP пакета всё ещё блокирует доставку последующих байтов всего TCP stream, затрагивая все HTTP/2 streams — transport-level head-of-line blocking.</p>
<p>Прокси могут завершать HTTP/2 от клиента и обращаться к upstream по HTTP/1.1; «используем HTTP/2» не значит end-to-end HTTP/2. Connection coalescing допускается при совместимых сертификате и адресе, что меняет ожидания о числе соединений. Не сохраняйте приложение, рассчитанное на один запрос на socket, без проверки.</p>

<h5>HTTP/3 и QUIC</h5>
<p>HTTP/3 использует QUIC поверх UDP. QUIC объединяет transport security на TLS 1.3, multiplexed streams, congestion control и возможность connection migration при смене сети через connection ID. Потеря пакета одного stream не обязана задержать доставку данных других streams так, как общий TCP byte stream. UDP может быть заблокирован или ограничен корпоративным firewall, поэтому браузер/сервер часто имеют fallback к TCP-based HTTP.</p>
<p>QUIC сложнее наблюдать сетевым middlebox и реализуется в user space, что позволяет быстрее обновлять transport поведение, но требует CPU и зрелой поддержки инфраструктуры. HTTP/3 не гарантирует меньшую latency в каждой сети: handshake, RTT, congestion, loss, CDN и конкретный workload важнее ярлыка версии.</p>

<h5>HTTP кеш, conditional requests и повторная валидация</h5>
<p><code class="i">Cache-Control: max-age</code> определяет свежесть; <code class="i">no-store</code> запрещает сохранение; <code class="i">private</code> ограничивает кеширование приватным клиентским кешем. <code class="i">ETag</code> и <code class="i">If-None-Match</code> позволяют revalidate и получить 304 без тела. <code class="i">Vary</code> добавляет request header в cache key; неосторожный Vary раздувает кеш, а недостающий вариативный ключ создаёт утечку/неверный контент.</p>
<p><code class="i">no-cache</code> не означает «не хранить» — оно требует проверки перед повторным использованием. CDN cache key должен учитывать действительно влияющие на ответ параметры, избегать произвольных cookies и не кэшировать персональные данные в shared cache. Cache poisoning возможен при расхождении того, что учитывает cache, и того, что использует origin.</p>

<h5>WebSocket и Server-Sent Events</h5>
<p>WebSocket начинается HTTP Upgrade handshake (для HTTP/1.1), затем работает как двунаправленный persistent connection с frames. Сервер может отправлять сообщения без нового запроса клиента. Нужны ping/pong heartbeat, idle timeout согласованный с proxy, reconnect с jitter, backpressure, ограничение размера frame, auth при соединении и повторная авторизация/истечение сессии. Балансировщик должен поддерживать Upgrade и draining long-lived connections.</p>
<p>SSE (Server-Sent Events) — однонаправленный поток server → browser через HTTP, с текстовыми event frames и встроенной reconnect моделью EventSource. Для обратного сообщения клиент делает обычный HTTP запрос. SSE легче проходит стандартные proxy, но нужно отключить buffering и учитывать connection limits/heartbeat. WebSocket выбирают при двунаправленной частой коммуникации, SSE — для односторонних уведомлений; polling остаётся проще для редких обновлений.</p>

<h5>gRPC, Protobuf и REST</h5>
<p>gRPC использует HTTP/2 и Protocol Buffers для типизированных контрактов и поддерживает unary, client-streaming, server-streaming и bidirectional-streaming RPC. Schema evolution требует правил: не переиспользовать номера полей, добавлять optional-compatible поля, сохранять неизвестные для старых clients там, где это нужно. Browser не говорит с обычным gRPC напрямую во всех сценариях; применяют gRPC-Web gateway или JSON transcoding.</p>
<p>RPC создаёт впечатление локального вызова, но сеть добавляет latency, partial failure, timeout, retry и сериализацию. Deadline нужно передавать вниз по цепочке; retry только для подходящих операций с backoff/jitter и ограниченным бюджетом. REST/JSON проще в браузерной экосистеме, gRPC полезен для typed service-to-service и streaming. Один не «лучше» без контекста команды, клиентов и инфраструктуры.</p>

<h5>Webhooks, MQTT, AMQP и Kafka: не смешивать гарантии</h5>
<p>Webhook — исходящий HTTP callback с подписью, повтором и доставкой «как минимум один раз» в типичных системах. Получатель должен проверять подпись по raw body, timestamp, replay window и idempotency key; отвечать быстро и переносить длительную обработку в очередь.</p>
<p>MQTT — лёгкий pub/sub протокол, часто используемый устройствами и нестабильными сетями; QoS 0/1/2 задаёт разные компромиссы доставки/дубликатов. AMQP брокер моделирует очереди, routing и acknowledgements. Kafka — распределённый append-only log с partitions, offsets и retention; consumer сам управляет позицией чтения. Kafka не является обычной очередью с удалением сообщения при ack: повторное чтение/retention встроены в модель. Выбор определяется потребностью в маршрутизации, replay, retention, throughput, latency и владении сообщением.</p>

<h5>Надёжность доставки: retry, deadline и идемпотентность</h5>
<p>Таймаут не сообщает, выполнилась ли операция: сервер мог записать заказ, а ответ потерялся. Клиентский retry способен создать дубликат. Idempotency key сохраняет результат операции по ключу и связывает его с payload; повтор возвращает исходный результат, а несовпадающее тело под тем же ключом отклоняется. Срок хранения ключа и атомарность с бизнес-транзакцией критичны.</p>
<p>Retry только transient errors, ограничивать попытки и общий deadline, использовать exponential backoff с jitter. Нельзя одновременно включить 5 retries в трёх слоях: множитель нагрузки способен вызвать retry storm. Circuit breaker и rate limit снижают каскад, но не заменяют корректную обработку неопределённого результата.</p>

<h5>Практические лаборатории протоколов</h5>
<div data-demo="protocol-lab"></div>
<ol><li>В Wireshark захватите DNS query/response, TCP handshake, TLS ClientHello и HTTP request к тестовому локальному серверу.</li><li>Сравните curl timings DNS/TCP/TLS/TTFB и объясните каждый интервал.</li><li>Через netcat отправьте строку частями и покажите, почему TCP не сохраняет границу write.</li><li>Сравните один HTTP/1.1, HTTP/2 и HTTP/3 запрос к поддерживающему серверу; проверьте negotiated protocol, fallback и latency.</li><li>Создайте SSE endpoint и WebSocket endpoint; проверьте proxy idle timeout, reconnect и heartbeat.</li><li>Смоделируйте webhook timeout после успешной записи, повторную доставку и дедупликацию ключом.</li><li>Сравните gRPC unary и streaming сценарий с REST JSON: контракт, framing, streaming, browser support и observability.</li></ol>
<p><b>Финальное упражнение:</b> нарисуйте последовательность запроса пользователя к API через DNS, CDN, TLS terminator, L7 load balancer, Node service, PostgreSQL и Kafka. На каждом переходе назовите протокол, timeout, retry owner, identity boundary, correlation ID и возможный partial failure.</p>
` }
